# Generated by Django 2.1.1 on 2018-10-07 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PorterJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(max_length=256)),
                ('video_source', models.PositiveSmallIntegerField(choices=[(0, 'Bilibili'), (1, 'Youku')], default=0)),
                ('youtube_id', models.CharField(blank=True, max_length=32, null=True)),
                ('video_file', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Downloading'), (2, 'Downloaded'), (3, 'Uploading'), (4, 'Success'), (5, 'Download Fail'), (6, 'Upload Fail'), (7, 'Duplicated')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('download_at', models.DateTimeField(blank=True, null=True)),
                ('upload_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('secret_file', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(related_name='videos', to='porter.VideoTag'),
        ),
        migrations.AddField(
            model_name='porterjob',
            name='video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='porter_job', to='porter.Video'),
        ),
        migrations.AddField(
            model_name='porterjob',
            name='youtube_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='porter_jobs', to='porter.YoutubeAccount'),
        ),
    ]
