# Generated by Django 2.1.1 on 2018-10-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_download_job', models.BooleanField(default=False)),
                ('start_upload_job', models.BooleanField(default=False)),
                ('start_bilibili_recommend_job', models.BooleanField(default=False)),
            ],
        ),
    ]
