# Generated by Django 2.1.1 on 2018-10-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='porterjob',
            name='video_file',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
