# Generated by Django 2.1.1 on 2018-10-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0002_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeaccount',
            name='upload_quota',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
