# Generated by Django 2.1.1 on 2018-10-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0002_porterjob_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='api_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='porterjob',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Downloading'), (2, 'Downloaded'), (3, 'Uploading'), (4, 'Success'), (5, 'Download Fail'), (6, 'Upload Fail')], default=0),
        ),
    ]
