# Generated by Django 2.1.1 on 2018-10-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0003_auto_20181002_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='porterjob',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Downloading'), (2, 'Downloaded'), (3, 'Uploading'), (4, 'Success'), (5, 'Download Fail'), (6, 'Upload Fail'), (7, 'Duplicated')], default=0),
        ),
    ]
