# Generated by Django 2.1.1 on 2018-10-16 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0004_auto_20181016_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('video_source', models.PositiveSmallIntegerField(choices=[(0, 'Bilibili'), (1, 'Youku')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('youtube_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_jobs', to='porter.YoutubeAccount')),
            ],
        ),
    ]
