# Generated by Django 2.1.1 on 2018-10-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0004_auto_20181004_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='porterjob',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
