# Generated by Django 2.1.1 on 2018-10-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0006_auto_20181018_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeaccount',
            name='credentials_file',
            field=models.CharField(default='x', max_length=256),
            preserve_default=False,
        ),
    ]
