# Generated by Django 2.1.1 on 2018-10-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0007_youtubeaccount_credentials_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porterjob',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Downloading'), (2, 'Downloaded'), (3, 'Uploading'), (4, 'Success'), (5, 'Download Fail'), (6, 'Upload Fail'), (7, 'Duplicated'), (8, 'API Error'), (9, 'Video Not Found'), (10, 'Partial')], default=0),
        ),
    ]
