# Generated by Django 2.1.1 on 2018-10-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0008_auto_20181021_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='porterjob',
            name='retried',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
