# Generated by Django 2.1.1 on 2018-11-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0010_auto_20181028_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='start_kuaiyinshi_recommend_job',
            field=models.BooleanField(default=False),
        ),
    ]
