# Generated by Django 2.1.1 on 2018-11-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0013_auto_20181109_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porterjob',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Downloading'), (2, 'Downloaded'), (3, 'Uploading'), (4, 'Success'), (5, 'Download Fail'), (6, 'Upload Fail'), (7, 'Duplicated'), (8, 'API Error'), (9, 'Video Not Found'), (10, 'Partial'), (14, 'Stop'), (15, 'Removed')], default=0),
        ),
    ]
