# Generated by Django 2.1.1 on 2018-11-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0015_youtubeaccount_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='start_kuaiyinshi_merge_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
