# Generated by Django 2.1.1 on 2018-12-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0016_auto_20181122_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualMergeJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id_list', models.CharField(max_length=512)),
                ('thumbnail_id_list', models.CharField(max_length=64)),
                ('video_title', models.CharField(blank=True, max_length=256, null=True)),
                ('video_description', models.TextField(blank=True, null=True)),
                ('video_tags', models.CharField(blank=True, default='搞笑,短视频,合集,美女,热门,精选,抖音,Tik Tok,Funny,Pretty girl,Short video,Featured', max_length=256, null=True)),
                ('video_source', models.PositiveSmallIntegerField(choices=[(3, '抖音'), (4, '美拍'), (5, '快手'), (6, '火山')], default=3)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Downloading'), (4, 'Success'), (14, 'Stop'), (17, 'Failed')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merge_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='channeljob',
            name='video_source',
            field=models.PositiveSmallIntegerField(choices=[(0, '哔哩哔哩'), (1, '优酷'), (2, '爱奇艺'), (3, '抖音'), (4, '美拍'), (5, '快手'), (6, '火山')], default=0),
        ),
        migrations.AlterField(
            model_name='porterjob',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Downloading'), (2, 'Downloaded'), (3, 'Uploading'), (4, 'Success'), (5, 'Download Fail'), (6, 'Upload Fail'), (7, 'Duplicated'), (8, 'API Error'), (9, 'Video Not Found'), (10, 'Partial'), (11, 'Pending Merge'), (12, 'Merged'), (13, 'API Exception'), (14, 'Stop'), (15, 'Removed'), (16, 'Pending Review')], default=0),
        ),
    ]
