# Generated by Django 2.1.1 on 2018-12-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0017_auto_20181204_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='porterjob',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
