# Generated by Django 2.1.1 on 2019-03-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0018_porterjob_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='channeljob',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
